In [ ]:
import pandas as pd
import numpy as np

# ============================================================
# 25-FLIGHT AIRLINE RECOVERY DATASET
# ============================================================

flights_25 = pd.DataFrame([
    ["F01","DEL","BOM",360,480,120,500000,1000],
    ["F02","BOM","BLR",540,640,0,500000,1000],
    ["F03","BLR","DEL",710,860,0,500000,1000],
    ["F04","DEL","CCU",390,510,0,500000,1000],
    ["F05","CCU","HYD",600,720,0,500000,1000],
    ["F06","HYD","DEL",780,900,0,500000,1000],
    ["F07","BLR","AMD",420,550,0,500000,1000],
    ["F08","AMD","DEL",610,730,0,500000,1000],
    ["F09","DEL","MAA",800,930,0,500000,1000],
    ["F10","MAA","HYD",450,550,0,500000,1000],
    ["F11","HYD","DEL",610,740,0,500000,1000],
    ["F12","DEL","AMD",800,920,150,500000,1000],
    ["F13","AMD","BOM",980,1090,0,500000,1000],
    ["F14","CCU","DEL",480,610,0,500000,1000],
    ["F15","DEL","BLR",670,800,0,500000,1000],
    ["F16","BLR","HYD",860,960,0,500000,1000],
    ["F17","BOM","DEL",400,520,0,500000,1000],
    ["F18","DEL","BOM",620,740,90,500000,1000],
    ["F19","BOM","CCU",920,1070,0,500000,1000],
    ["F20","HYD","BOM",430,550,0,500000,1000],
    ["F21","BOM","DEL",610,730,0,500000,1000],
    ["F22","DEL","BLR",800,950,0,500000,1000],
    ["F23","DEL","AMD",500,620,0,500000,1000],
    ["F24","AMD","HYD",680,800,0,500000,1000],
    ["F25","HYD","DEL",870,990,0,500000,1000],
], columns=[
    "flight_id",
    "origin",
    "destination",
    "std",
    "sta",
    "forced_delay",
    "c_cancel",
    "c_delay_per_min"
])

print("Flights loaded:", len(flights_25))
display(flights_25)

Flights loaded: 25

,flight_id,origin,destination,std,sta,forced_delay,c_cancel,c_delay_per_min
0,F01,DEL,BOM,360,480,120,500000,1000
1,F02,BOM,BLR,540,640,0,500000,1000
2,F03,BLR,DEL,710,860,0,500000,1000
3,F04,DEL,CCU,390,510,0,500000,1000
4,F05,CCU,HYD,600,720,0,500000,1000
5,F06,HYD,DEL,780,900,0,500000,1000
6,F07,BLR,AMD,420,550,0,500000,1000
7,F08,AMD,DEL,610,730,0,500000,1000
8,F09,DEL,MAA,800,930,0,500000,1000
9,F10,MAA,HYD,450,550,0,500000,1000
10,F11,HYD,DEL,610,740,0,500000,1000
11,F12,DEL,AMD,800,920,150,500000,1000
12,F13,AMD,BOM,980,1090,0,500000,1000
13,F14,CCU,DEL,480,610,0,500000,1000
14,F15,DEL,BLR,670,800,0,500000,1000
15,F16,BLR,HYD,860,960,0,500000,1000
16,F17,BOM,DEL,400,520,0,500000,1000
17,F18,DEL,BOM,620,740,90,500000,1000
18,F19,BOM,CCU,920,1070,0,500000,1000
19,F20,HYD,BOM,430,550,0,500000,1000
20,F21,BOM,DEL,610,730,0,500000,1000
21,F22,DEL,BLR,800,950,0,500000,1000
22,F23,DEL,AMD,500,620,0,500000,1000
23,F24,AMD,HYD,680,800,0,500000,1000
24,F25,HYD,DEL,870,990,0,500000,1000

In [ ]:
# ============================================================
# AIRCRAFT DATA
# ============================================================

aircraft_25 = pd.DataFrame([
    ["AC01", "A320", "DEL", 360, 45, "AVAILABLE", None, None],
    ["AC02", "A320", "DEL", 375, 45, "MAINTENANCE", 510, 570],
    ["AC03", "A320", "BLR", 390, 45, "AVAILABLE", None, None],
    ["AC04", "A321", "MAA", 405, 45, "AVAILABLE", None, None],
    ["AC05", "A320", "CCU", 420, 45, "AVAILABLE", None, None],
    ["AC06", "A320", "BOM", 435, 45, "AOG", 600, 900],
    ["AC07", "A321", "HYD", 450, 45, "AVAILABLE", None, None],
    ["AC08", "A320", "DEL", 465, 45, "AVAILABLE", None, None],
], columns=[
    "aircraft_id",
    "aircraft_type",
    "initial_location",
    "available_time",
    "turnaround_time_min",
    "status",
    "unavailability_start",
    "unavailability_end"
])

print("Aircraft loaded:", len(aircraft_25))
display(aircraft_25)

Aircraft loaded: 8

,aircraft_id,aircraft_type,initial_location,available_time,turnaround_time_min,status,unavailability_start,unavailability_end
0,AC01,A320,DEL,360,45,AVAILABLE,NaN,NaN
1,AC02,A320,DEL,375,45,MAINTENANCE,510.0,570.0
2,AC03,A320,BLR,390,45,AVAILABLE,NaN,NaN
3,AC04,A321,MAA,405,45,AVAILABLE,NaN,NaN
4,AC05,A320,CCU,420,45,AVAILABLE,NaN,NaN
5,AC06,A320,BOM,435,45,AOG,600.0,900.0
6,AC07,A321,HYD,450,45,AVAILABLE,NaN,NaN
7,AC08,A320,DEL,465,45,AVAILABLE,NaN,NaN

In [ ]:
# ============================================================
# CREW DATA
# ============================================================

crew_25 = pd.DataFrame([
    ["CR01", "Captain",       "DEL", 390, 720, 480, 30],
    ["CR02", "First Officer", "DEL", 420, 720, 480, 30],
    ["CR03", "Captain",       "DEL", 450, 720, 480, 30],
    ["CR04", "First Officer", "DEL", 360, 720, 480, 30],
    ["CR05", "Captain",       "BOM", 390, 720, 480, 30],
    ["CR06", "First Officer", "BOM", 420, 720, 480, 30],
    ["CR07", "Captain",       "BLR", 450, 720, 480, 30],
    ["CR08", "First Officer", "BLR", 360, 720, 480, 30],
    ["CR09", "Captain",       "MAA", 390, 720, 480, 30],
    ["CR10", "First Officer", "MAA", 420, 720, 480, 30],
    ["CR11", "Captain",       "CCU", 450, 720, 480, 30],
    ["CR12", "First Officer", "CCU", 360, 720, 480, 30],
    ["CR13", "Captain",       "HYD", 390, 720, 480, 30],
    ["CR14", "First Officer", "HYD", 420, 720, 480, 30],
    ["CR15", "Captain",       "AMD", 450, 720, 480, 30],
    ["CR16", "First Officer", "DEL", 360, 720, 480, 30],
], columns=[
    "crew_id",
    "role",
    "home_base",
    "available_time",
    "max_duty_mins",
    "max_flight_mins",
    "min_rest_mins"
])

print("Crew loaded:", len(crew_25))
display(crew_25)

Crew loaded: 16

,crew_id,role,home_base,available_time,max_duty_mins,max_flight_mins,min_rest_mins
0,CR01,Captain,DEL,390,720,480,30
1,CR02,First Officer,DEL,420,720,480,30
2,CR03,Captain,DEL,450,720,480,30
3,CR04,First Officer,DEL,360,720,480,30
4,CR05,Captain,BOM,390,720,480,30
5,CR06,First Officer,BOM,420,720,480,30
6,CR07,Captain,BLR,450,720,480,30
7,CR08,First Officer,BLR,360,720,480,30
8,CR09,Captain,MAA,390,720,480,30
9,CR10,First Officer,MAA,420,720,480,30
10,CR11,Captain,CCU,450,720,480,30
11,CR12,First Officer,CCU,360,720,480,30
12,CR13,Captain,HYD,390,720,480,30
13,CR14,First Officer,HYD,420,720,480,30
14,CR15,Captain,AMD,450,720,480,30
15,CR16,First Officer,DEL,360,720,480,30

In [ ]:
# ============================================================
# BASIC DATA VALIDATION
# ============================================================

print("=== DATA VALIDATION ===")

# Flight count
assert len(flights_25) == 25, "Expected 25 flights"
assert len(aircraft_25) == 8, "Expected 8 aircraft"
assert len(crew_25) == 16, "Expected 16 crew units"

# No flight has same origin and destination
same_airport = flights_25[
    flights_25["origin"] == flights_25["destination"]
]

print("Flights with same origin/destination:")
display(same_airport)

# Arrival must be after departure
invalid_times = flights_25[
    flights_25["sta"] <= flights_25["std"]
]

print("Flights with invalid timing:")
display(invalid_times)

# Forced delay must be non-negative
invalid_delay = flights_25[
    flights_25["forced_delay"] < 0
]

print("Flights with negative forced delay:")
display(invalid_delay)

print("\n=== SUMMARY ===")
print("Flights:", len(flights_25))
print("Aircraft:", len(aircraft_25))
print("Crew:", len(crew_25))

if len(same_airport) == 0 and len(invalid_times) == 0 and len(invalid_delay) == 0:
    print("✓ Basic validation passed")
else:
    print("⚠ Validation found issues")

=== DATA VALIDATION ===
Flights with same origin/destination:

Empty DataFrame
Columns: [flight_id, origin, destination, std, sta, forced_delay, c_cancel, c_delay_per_min]
Index: []

Flights with invalid timing:

Empty DataFrame
Columns: [flight_id, origin, destination, std, sta, forced_delay, c_cancel, c_delay_per_min]
Index: []

Flights with negative forced delay:

Empty DataFrame
Columns: [flight_id, origin, destination, std, sta, forced_delay, c_cancel, c_delay_per_min]
Index: []

=== SUMMARY ===
Flights: 25
Aircraft: 8
Crew: 16
✓ Basic validation passed

In [ ]:
# ============================================================
# PRESOLVER RULE 1:
# AIRCRAFT FIRST-FLIGHT FEASIBILITY
# ============================================================

aircraft_first_results = []

for _, ac in aircraft_25.iterrows():

    for _, flight in flights_25.iterrows():

        reasons = []

        # ----------------------------------------------------
        # Rule 1: Initial location must match flight origin
        # ----------------------------------------------------
        if ac["initial_location"] != flight["origin"]:
            reasons.append("wrong_initial_location")

        # ----------------------------------------------------
        # Rule 2: Aircraft must be available before departure
        # ----------------------------------------------------
        if ac["available_time"] > flight["std"]:
            reasons.append("aircraft_not_available")

        # ----------------------------------------------------
        # Rule 3: Check maintenance / AOG window
        # ----------------------------------------------------
        if pd.notna(ac["unavailability_start"]) and pd.notna(ac["unavailability_end"]):

            # Flight occupies the aircraft from STD to STA.
            # If its operating interval overlaps the
            # unavailability interval, it is infeasible.
            flight_start = flight["std"]
            flight_end = flight["sta"] + flight["forced_delay"]

            unavailable_start = ac["unavailability_start"]
            unavailable_end = ac["unavailability_end"]

            overlap = (
                flight_start < unavailable_end
                and flight_end > unavailable_start
            )

            if overlap:
                reasons.append("technical_or_maintenance_hold")

        feasible = len(reasons) == 0

        aircraft_first_results.append({
            "aircraft_id": ac["aircraft_id"],
            "flight_id": flight["flight_id"],
            "feasible": feasible,
            "reason": ", ".join(reasons)
        })

aircraft_first_df = pd.DataFrame(aircraft_first_results)

print("=== AIRCRAFT FIRST-FLIGHT FEASIBILITY ===")

print("\nFEASIBLE:")
display(
    aircraft_first_df[
        aircraft_first_df["feasible"] == True
    ]
)

print("\nPRUNED:")
display(
    aircraft_first_df[
        aircraft_first_df["feasible"] == False
    ]
)

print("\n=== SUMMARY ===")
print("Total combinations:", len(aircraft_first_df))
print(
    "Feasible:",
    aircraft_first_df["feasible"].sum()
)
print(
    "Pruned:",
    (~aircraft_first_df["feasible"]).sum()
)

=== AIRCRAFT FIRST-FLIGHT FEASIBILITY ===

FEASIBLE:

    aircraft_id flight_id  feasible reason
0          AC01       F01      True
3          AC01       F04      True
8          AC01       F09      True
11         AC01       F12      True
14         AC01       F15      True
17         AC01       F18      True
21         AC01       F22      True
22         AC01       F23      True
28         AC02       F04      True
33         AC02       F09      True
36         AC02       F12      True
39         AC02       F15      True
42         AC02       F18      True
46         AC02       F22      True
52         AC03       F03      True
56         AC03       F07      True
65         AC03       F16      True
84         AC04       F10      True
104        AC05       F05      True
113        AC05       F14      True
143        AC06       F19      True
155        AC07       F06      True
160        AC07       F11      True
174        AC07       F25      True
183        AC08       F09      True
186        AC08       F12      True
189        AC08       F15      True
192        AC08       F18      True
196        AC08       F22      True
197        AC08       F23      True

PRUNED:

,aircraft_id,flight_id,feasible,reason
1,AC01,F02,False,wrong_initial_location
2,AC01,F03,False,wrong_initial_location
4,AC01,F05,False,wrong_initial_location
5,AC01,F06,False,wrong_initial_location
6,AC01,F07,False,wrong_initial_location
...,...,...,...,...
193,AC08,F19,False,wrong_initial_location
194,AC08,F20,False,"wrong_initial_location, aircraft_not_available"
195,AC08,F21,False,wrong_initial_location
198,AC08,F24,False,wrong_initial_location
199,AC08,F25,False,wrong_initial_location

=== SUMMARY ===
Total combinations: 200
Feasible: 30
Pruned: 170

In [ ]:
# ============================================================
# PRESOLVER RULE 2:
# AIRCRAFT TRANSITION FEASIBILITY
# ============================================================

aircraft_transition_results = []

for _, ac in aircraft_25.iterrows():

    for i, f1 in flights_25.iterrows():

        for j, f2 in flights_25.iterrows():

            if i == j:
                continue

            reasons = []

            # ------------------------------------------------
            # Rule 1: Airport continuity
            # ------------------------------------------------
            if f1["destination"] != f2["origin"]:
                reasons.append("airport_mismatch")

            # ------------------------------------------------
            # Rule 2: Calculate actual arrival of F1
            # ------------------------------------------------
            f1_actual_arrival = f1["sta"] + f1["forced_delay"]

            # ------------------------------------------------
            # Rule 3: Calculate available time before F2
            # ------------------------------------------------
            ground_time = f2["std"] - f1_actual_arrival

            if ground_time < ac["turnaround_time_min"]:
                reasons.append("insufficient_turnaround")

            # ------------------------------------------------
            # Rule 4: Check aircraft maintenance/AOG
            # during F2
            # ------------------------------------------------
            if (
                pd.notna(ac["unavailability_start"])
                and pd.notna(ac["unavailability_end"])
            ):

                f2_start = f2["std"]
                f2_end = f2["sta"] + f2["forced_delay"]

                overlap = (
                    f2_start < ac["unavailability_end"]
                    and f2_end > ac["unavailability_start"]
                )

                if overlap:
                    reasons.append("technical_or_maintenance_hold")

            feasible = len(reasons) == 0

            aircraft_transition_results.append({
                "aircraft_id": ac["aircraft_id"],
                "from": f1["flight_id"],
                "to": f2["flight_id"],
                "feasible": feasible,
                "reason": ", ".join(reasons),
                "ground_time": ground_time
            })

aircraft_transition_df = pd.DataFrame(
    aircraft_transition_results
)

print("=== AIRCRAFT TRANSITION FEASIBILITY ===")

print("\nFEASIBLE TRANSITIONS:")
display(
    aircraft_transition_df[
        aircraft_transition_df["feasible"] == True
    ]
)

print("\nPRUNED TRANSITIONS:")
display(
    aircraft_transition_df[
        aircraft_transition_df["feasible"] == False
    ]
)

print("\n=== SUMMARY ===")
print(
    "Total aircraft-flight transitions checked:",
    len(aircraft_transition_df)
)

print(
    "Feasible:",
    aircraft_transition_df["feasible"].sum()
)

print(
    "Pruned:",
    (~aircraft_transition_df["feasible"]).sum()
)

=== AIRCRAFT TRANSITION FEASIBILITY ===

FEASIBLE TRANSITIONS:

     aircraft_id from   to  feasible reason  ground_time
17          AC01  F01  F19      True                 320
25          AC01  F02  F03      True                  70
38          AC01  F02  F16      True                 220
75          AC01  F04  F05      True                  90
100         AC01  F05  F06      True                  60
...          ...  ...  ...       ...    ...          ...
4691        AC08  F21  F12      True                  70
4700        AC08  F21  F22      True                  70
4740        AC08  F23  F13      True                 360
4750        AC08  F23  F24      True                  60
4775        AC08  F24  F25      True                  70

[264 rows x 6 columns]

PRUNED TRANSITIONS:

,aircraft_id,from,to,feasible,reason,ground_time
0,AC01,F01,F02,False,insufficient_turnaround,-60
1,AC01,F01,F03,False,airport_mismatch,110
2,AC01,F01,F04,False,"airport_mismatch, insufficient_turnaround",-210
3,AC01,F01,F05,False,"airport_mismatch, insufficient_turnaround",0
4,AC01,F01,F06,False,airport_mismatch,180
...,...,...,...,...,...,...
4795,AC08,F25,F20,False,"airport_mismatch, insufficient_turnaround",-560
4796,AC08,F25,F21,False,"airport_mismatch, insufficient_turnaround",-380
4797,AC08,F25,F22,False,insufficient_turnaround,-190
4798,AC08,F25,F23,False,insufficient_turnaround,-490
4799,AC08,F25,F24,False,"airport_mismatch, insufficient_turnaround",-310

=== SUMMARY ===
Total aircraft-flight transitions checked: 4800
Feasible: 264
Pruned: 4536

In [ ]:
# ============================================================
# PRESOLVER RULE 3:
# BUILD FLIGHT-LEVEL ROUTING ARCS
#
# An arc F1 -> F2 exists only if at least one aircraft can:
#   1. Start with F1
#   2. Perform the transition F1 -> F2
#
# Aircraft assignment remains implicit.
# ============================================================

valid_flight_arcs = []

# ------------------------------------------------------------
# Step 1: Get aircraft-flight pairs that are feasible as
#         FIRST flights
# ------------------------------------------------------------

feasible_first = aircraft_first_df[
    aircraft_first_df["feasible"] == True
].copy()

# ------------------------------------------------------------
# Step 2: Get aircraft transitions that are feasible
# ------------------------------------------------------------

feasible_transitions = aircraft_transition_df[
    aircraft_transition_df["feasible"] == True
].copy()

# ------------------------------------------------------------
# Step 3: Match them by aircraft + first flight
# ------------------------------------------------------------

for _, transition in feasible_transitions.iterrows():

    aircraft_id = transition["aircraft_id"]
    from_flight = transition["from"]
    to_flight = transition["to"]

    # Check whether this aircraft can actually START
    # with the first flight.
    can_start = (
        (feasible_first["aircraft_id"] == aircraft_id) &
        (feasible_first["flight_id"] == from_flight)
    ).any()

    if not can_start:
        continue

    valid_flight_arcs.append({
        "from": from_flight,
        "to": to_flight,
        "feasible": True,
        "supporting_aircraft": aircraft_id,
        "ground_time": transition["ground_time"]
    })

# ------------------------------------------------------------
# Step 4: Combine duplicate flight-level arcs
#
# Multiple aircraft may support the same F1 -> F2 arc.
# We keep ONE flight-level arc and list all supporting aircraft.
# ------------------------------------------------------------

if valid_flight_arcs:

    flight_arc_temp_df = pd.DataFrame(valid_flight_arcs)

    flight_arc_df = (
        flight_arc_temp_df
        .groupby(["from", "to"], as_index=False)
        .agg(
            feasible=("feasible", "max"),
            supporting_aircraft=(
                "supporting_aircraft",
                lambda x: ", ".join(sorted(x.unique()))
            ),
            aircraft_count=(
                "supporting_aircraft",
                "nunique"
            ),
            ground_time=("ground_time", "first")
        )
    )

else:

    flight_arc_df = pd.DataFrame(
        columns=[
            "from",
            "to",
            "feasible",
            "supporting_aircraft",
            "aircraft_count",
            "ground_time"
        ]
    )

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("=== VALID FLIGHT-LEVEL ROUTING ARCS ===")

display(
    flight_arc_df
    .sort_values(["from", "to"])
    .reset_index(drop=True)
)

print("\n=== SUMMARY ===")
print(
    "Valid flight-level arcs:",
    len(flight_arc_df)
)

print(
    "Aircraft-supported transitions used:",
    len(valid_flight_arcs)
)

=== VALID FLIGHT-LEVEL ROUTING ARCS ===

   from   to  feasible supporting_aircraft  aircraft_count  ground_time
0   F01  F19      True                AC01               1          320
1   F04  F05      True          AC01, AC02               2           90
2   F05  F06      True                AC05               1           60
3   F05  F25      True                AC05               1          150
4   F07  F08      True                AC03               1           60
5   F07  F13      True                AC03               1          430
6   F07  F24      True                AC03               1          130
7   F10  F06      True                AC04               1          230
8   F10  F11      True                AC04               1           60
9   F10  F25      True                AC04               1          320
10  F11  F09      True                AC07               1           60
11  F11  F12      True                AC07               1           60
12  F11  F22      True                AC07               1           60
13  F14  F09      True                AC05               1          190
14  F14  F12      True                AC05               1          190
15  F14  F15      True                AC05               1           60
16  F14  F22      True                AC05               1          190
17  F15  F16      True    AC01, AC02, AC08               3           60
18  F18  F19      True    AC01, AC02, AC08               3           90
19  F23  F13      True          AC01, AC08               2          360
20  F23  F24      True          AC01, AC08               2           60

=== SUMMARY ===
Valid flight-level arcs: 21
Aircraft-supported transitions used: 28

In [ ]:
# ============================================================
# PRESOLVER RULE 4:
# CREW FIRST-FLIGHT FEASIBILITY
# ============================================================

crew_first_results = []

for _, cr in crew_25.iterrows():

    for _, flight in flights_25.iterrows():

        reasons = []

        # ----------------------------------------------------
        # Rule 1: Crew home base must match flight origin
        # ----------------------------------------------------
        if cr["home_base"] != flight["origin"]:
            reasons.append("wrong_home_base")

        # ----------------------------------------------------
        # Rule 2: Crew must be available before departure
        # ----------------------------------------------------
        if cr["available_time"] > flight["std"]:
            reasons.append("crew_not_available")

        # ----------------------------------------------------
        # Rule 3: Flight duration must not exceed
        # maximum allowed flight time
        # ----------------------------------------------------
        flight_duration = (
            flight["sta"] - flight["std"]
        )

        if flight_duration > cr["max_flight_mins"]:
            reasons.append("exceeds_max_flight_time")

        feasible = len(reasons) == 0

        crew_first_results.append({
            "crew_id": cr["crew_id"],
            "flight_id": flight["flight_id"],
            "feasible": feasible,
            "reason": ", ".join(reasons)
        })

crew_first_df = pd.DataFrame(crew_first_results)

print("=== CREW FIRST-FLIGHT FEASIBILITY ===")

print("\nFEASIBLE:")
display(
    crew_first_df[
        crew_first_df["feasible"] == True
    ]
)

print("\nPRUNED:")
display(
    crew_first_df[
        crew_first_df["feasible"] == False
    ]
)

print("\n=== SUMMARY ===")
print(
    "Total combinations:",
    len(crew_first_df)
)

print(
    "Feasible:",
    crew_first_df["feasible"].sum()
)

print(
    "Pruned:",
    (~crew_first_df["feasible"]).sum()
)

=== CREW FIRST-FLIGHT FEASIBILITY ===

FEASIBLE:

    crew_id flight_id  feasible reason
3      CR01       F04      True
8      CR01       F09      True
11     CR01       F12      True
14     CR01       F15      True
17     CR01       F18      True
..      ...       ...       ...    ...
386    CR16       F12      True
389    CR16       F15      True
392    CR16       F18      True
396    CR16       F22      True
397    CR16       F23      True

[64 rows x 4 columns]

PRUNED:

    crew_id flight_id  feasible              reason
0      CR01       F01     False  crew_not_available
1      CR01       F02     False     wrong_home_base
2      CR01       F03     False     wrong_home_base
4      CR01       F05     False     wrong_home_base
5      CR01       F06     False     wrong_home_base
..      ...       ...       ...                 ...
393    CR16       F19     False     wrong_home_base
394    CR16       F20     False     wrong_home_base
395    CR16       F21     False     wrong_home_base
398    CR16       F24     False     wrong_home_base
399    CR16       F25     False     wrong_home_base

[336 rows x 4 columns]

=== SUMMARY ===
Total combinations: 400
Feasible: 64
Pruned: 336

In [ ]:
# ============================================================
# PRESOLVER RULE 5:
# CREW TRANSITION FEASIBILITY
# ============================================================

crew_transition_results = []

for _, cr in crew_25.iterrows():

    for _, f1 in flights_25.iterrows():

        for _, f2 in flights_25.iterrows():

            if f1["flight_id"] == f2["flight_id"]:
                continue

            reasons = []

            # ------------------------------------------------
            # Rule 1: Crew must be able to operate F1
            # as a first flight
            # ------------------------------------------------
            f1_first = crew_first_df[
                (crew_first_df["crew_id"] == cr["crew_id"]) &
                (crew_first_df["flight_id"] == f1["flight_id"]) &
                (crew_first_df["feasible"] == True)
            ]

            if f1_first.empty:
                reasons.append("cannot_start_first_flight")

            # ------------------------------------------------
            # Rule 2: Flight continuity
            # Crew can only continue if the next flight
            # starts from the previous flight's destination.
            # ------------------------------------------------
            if f1["destination"] != f2["origin"]:
                reasons.append("airport_mismatch")

            # ------------------------------------------------
            # Rule 3: Rest between flights
            # ------------------------------------------------
            f1_actual_arrival = (
                f1["sta"] + f1["forced_delay"]
            )

            ground_time = (
                f2["std"] - f1_actual_arrival
            )

            if ground_time < cr["min_rest_mins"]:
                reasons.append("insufficient_rest")

            # ------------------------------------------------
            # Rule 4: Total duty time
            # From beginning of F1 to end of F2
            # ------------------------------------------------
            duty_time = (
                f2["sta"] + f2["forced_delay"]
                - f1["std"]
            )

            if duty_time > cr["max_duty_mins"]:
                reasons.append("exceeds_max_duty_time")

            feasible = len(reasons) == 0

            crew_transition_results.append({
                "crew_id": cr["crew_id"],
                "from": f1["flight_id"],
                "to": f2["flight_id"],
                "feasible": feasible,
                "reason": ", ".join(reasons),
                "ground_time": ground_time,
                "duty_time": duty_time
            })

crew_transition_df = pd.DataFrame(
    crew_transition_results
)

print("=== CREW TRANSITION FEASIBILITY ===")

print("\nFEASIBLE TRANSITIONS:")
display(
    crew_transition_df[
        crew_transition_df["feasible"] == True
    ]
)

print("\nPRUNED TRANSITIONS:")
display(
    crew_transition_df[
        crew_transition_df["feasible"] == False
    ]
)

print("\n=== SUMMARY ===")
print(
    "Total crew-flight transitions checked:",
    len(crew_transition_df)
)

print(
    "Feasible:",
    crew_transition_df["feasible"].sum()
)

print(
    "Pruned:",
    (~crew_transition_df["feasible"]).sum()
)

=== CREW TRANSITION FEASIBILITY ===

FEASIBLE TRANSITIONS:

     crew_id from   to  feasible reason  ground_time  duty_time
75      CR01  F04  F05      True                  90        330
350     CR01  F15  F16      True                  60        290
425     CR01  F18  F19      True                  90        450
540     CR01  F23  F13      True                 360        590
550     CR01  F23  F24      True                  60        300
...      ...  ...  ...       ...    ...          ...        ...
9075    CR16  F04  F05      True                  90        330
9350    CR16  F15  F16      True                  60        290
9425    CR16  F18  F19      True                  90        450
9540    CR16  F23  F13      True                 360        590
9550    CR16  F23  F24      True                  60        300

[75 rows x 7 columns]

PRUNED TRANSITIONS:

,crew_id,from,to,feasible,reason,ground_time,duty_time
0,CR01,F01,F02,False,"cannot_start_first_flight, insufficient_rest",-60,280
1,CR01,F01,F03,False,"cannot_start_first_flight, airport_mismatch",110,500
2,CR01,F01,F04,False,"cannot_start_first_flight, airport_mismatch, i...",-210,150
3,CR01,F01,F05,False,"cannot_start_first_flight, airport_mismatch, i...",0,360
4,CR01,F01,F06,False,"cannot_start_first_flight, airport_mismatch",180,540
...,...,...,...,...,...,...,...
9595,CR16,F25,F20,False,"cannot_start_first_flight, airport_mismatch, i...",-560,-320
9596,CR16,F25,F21,False,"cannot_start_first_flight, airport_mismatch, i...",-380,-140
9597,CR16,F25,F22,False,"cannot_start_first_flight, insufficient_rest",-190,80
9598,CR16,F25,F23,False,"cannot_start_first_flight, insufficient_rest",-490,-250
9599,CR16,F25,F24,False,"cannot_start_first_flight, airport_mismatch, i...",-310,-70

=== SUMMARY ===
Total crew-flight transitions checked: 9600
Feasible: 75
Pruned: 9525

In [ ]:
# ============================================================
# PRESOLVER RULE 6:
# FINAL FLIGHT ROUTING FEASIBILITY
#
# A flight transition is valid only when:
#   1. At least one aircraft can perform it
#   2. At least one crew member can perform it
#
# Aircraft and crew assignments remain implicit.
# ============================================================

# ------------------------------------------------------------
# Aircraft-feasible transitions
# ------------------------------------------------------------

aircraft_feasible = aircraft_transition_df[
    aircraft_transition_df["feasible"] == True
].copy()

# ------------------------------------------------------------
# Crew-feasible transitions
# ------------------------------------------------------------

crew_feasible = crew_transition_df[
    crew_transition_df["feasible"] == True
].copy()

# ------------------------------------------------------------
# Get unique flight pairs for each resource
# ------------------------------------------------------------

aircraft_arcs = set(
    zip(
        aircraft_feasible["from"],
        aircraft_feasible["to"]
    )
)

crew_arcs = set(
    zip(
        crew_feasible["from"],
        crew_feasible["to"]
    )
)

# ------------------------------------------------------------
# Final intersection
# ------------------------------------------------------------

final_arcs = sorted(
    aircraft_arcs.intersection(crew_arcs)
)

# ------------------------------------------------------------
# Build final routing table
# ------------------------------------------------------------

final_routing_results = []

for from_flight, to_flight in final_arcs:

    # Aircraft supporting this transition
    supporting_aircraft = sorted(
        aircraft_feasible[
            (aircraft_feasible["from"] == from_flight) &
            (aircraft_feasible["to"] == to_flight)
        ]["aircraft_id"].unique()
    )

    # Crew supporting this transition
    supporting_crew = sorted(
        crew_feasible[
            (crew_feasible["from"] == from_flight) &
            (crew_feasible["to"] == to_flight)
        ]["crew_id"].unique()
    )

    # Ground time
    ground_time = aircraft_feasible[
        (aircraft_feasible["from"] == from_flight) &
        (aircraft_feasible["to"] == to_flight)
    ]["ground_time"].iloc[0]

    final_routing_results.append({
        "from": from_flight,
        "to": to_flight,
        "feasible": True,
        "supporting_aircraft": ", ".join(supporting_aircraft),
        "supporting_crew": ", ".join(supporting_crew),
        "aircraft_count": len(supporting_aircraft),
        "crew_count": len(supporting_crew),
        "ground_time": ground_time
    })

final_routing_df = pd.DataFrame(
    final_routing_results
)

# ------------------------------------------------------------
# Display final result
# ------------------------------------------------------------

print("=== FINAL FEASIBLE ROUTING ARCS ===")

display(
    final_routing_df
    .sort_values(["from", "to"])
    .reset_index(drop=True)
)

print("\n=== SUMMARY ===")

print(
    "Aircraft-feasible flight arcs:",
    len(aircraft_arcs)
)

print(
    "Crew-feasible flight arcs:",
    len(crew_arcs)
)

print(
    "Final feasible routing arcs:",
    len(final_arcs)
)

=== FINAL FEASIBLE ROUTING ARCS ===

,from,to,feasible,supporting_aircraft,supporting_crew,aircraft_count,crew_count,ground_time
0,F01,F19,True,"AC01, AC02, AC03, AC04, AC05, AC06, AC07, AC08","CR04, CR16",8,2,320
1,F02,F03,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR05, CR06",7,2,70
2,F02,F16,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR05, CR06",7,2,220
3,F04,F05,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR01, CR04, CR16",7,3,90
4,F05,F06,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,60
5,F05,F25,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,150
6,F07,F08,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR08,7,1,60
7,F07,F13,True,"AC01, AC02, AC03, AC04, AC05, AC06, AC07, AC08",CR08,8,1,430
8,F07,F24,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR08,7,1,130
9,F08,F09,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR15,7,1,70
10,F08,F12,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR15,7,1,70
11,F08,F22,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR15,7,1,70
12,F10,F06,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR09, CR10",7,2,230
13,F10,F11,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR09, CR10",7,2,60
14,F10,F25,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR09, CR10",7,2,320
15,F11,F09,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR13, CR14",7,2,60
16,F11,F12,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR13, CR14",7,2,60
17,F11,F22,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR13, CR14",7,2,60
18,F14,F09,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,190
19,F14,F12,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,190
20,F14,F15,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,60
21,F14,F22,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR11, CR12",7,2,190
22,F15,F16,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR01, CR02, CR03, CR04, CR16",7,5,60
23,F17,F09,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR05,7,1,280
24,F17,F12,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR05,7,1,280
25,F17,F15,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR05,7,1,150
26,F17,F18,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR05,7,1,100
27,F17,F22,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR05,7,1,280
28,F18,F19,True,"AC01, AC02, AC03, AC04, AC05, AC06, AC07, AC08","CR01, CR02, CR03, CR04, CR16",8,5,90
29,F20,F19,True,"AC01, AC02, AC03, AC04, AC05, AC06, AC07, AC08","CR13, CR14",8,2,370
30,F20,F21,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR13, CR14",7,2,60
31,F21,F09,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR05, CR06",7,2,70
32,F21,F12,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR05, CR06",7,2,70
33,F21,F22,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR05, CR06",7,2,70
34,F23,F13,True,"AC01, AC02, AC03, AC04, AC05, AC06, AC07, AC08","CR01, CR02, CR03, CR04, CR16",8,5,360
35,F23,F24,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08","CR01, CR02, CR03, CR04, CR16",7,5,60
36,F24,F25,True,"AC01, AC02, AC03, AC04, AC05, AC07, AC08",CR15,7,1,70

=== SUMMARY ===
Aircraft-feasible flight arcs: 37
Crew-feasible flight arcs: 37
Final feasible routing arcs: 37

In [ ]:
# ============================================================
# MILP MODEL: DECISION VARIABLES
# ============================================================

from scipy.optimize import milp, LinearConstraint, Bounds
from scipy.sparse import lil_matrix
import numpy as np

# ------------------------------------------------------------
# 1. Cancellation variables
# ------------------------------------------------------------

cancel_vars = [
    f"x_cancel_{flight_id}"
    for flight_id in flights_25["flight_id"]
]

# ------------------------------------------------------------
# 2. Delay variables
# ------------------------------------------------------------

delay_vars = [
    f"d_{flight_id}"
    for flight_id in flights_25["flight_id"]
]

# ------------------------------------------------------------
# 3. Routing arc variables
#
# final_arcs contains tuples:
# ('F01', 'F19')
# ('F02', 'F03')
# etc.
# ------------------------------------------------------------

arc_vars = [
    f"x_arc_{from_flight}_{to_flight}"
    for from_flight, to_flight in final_arcs
]

# ------------------------------------------------------------
# 4. Combine all variables
# ------------------------------------------------------------

variable_names = (
    cancel_vars
    + delay_vars
    + arc_vars
)

# ------------------------------------------------------------
# 5. Variable types
#
# B = Binary
# C = Continuous
# ------------------------------------------------------------

variable_types = (
    ["B"] * len(cancel_vars)
    + ["C"] * len(delay_vars)
    + ["B"] * len(arc_vars)
)

# ------------------------------------------------------------
# 6. Lower bounds
# ------------------------------------------------------------

lower_bounds = (
    [0.0] * len(cancel_vars)
    + [0.0] * len(delay_vars)
    + [0.0] * len(arc_vars)
)

# ------------------------------------------------------------
# 7. Upper bounds
#
# Cancellation: 0 or 1
# Delay: maximum 60 minutes
# Routing arc: 0 or 1
# ------------------------------------------------------------

upper_bounds = (
    [1.0] * len(cancel_vars)
    + [60.0] * len(delay_vars)
    + [1.0] * len(arc_vars)
)

# ------------------------------------------------------------
# 8. Display model size
# ------------------------------------------------------------

print("=== MILP DECISION VARIABLES ===")

print(f"Cancellation variables : {len(cancel_vars)}")
print(f"Delay variables        : {len(delay_vars)}")
print(f"Routing arc variables  : {len(arc_vars)}")
print(f"Total decision variables: {len(variable_names)}")

# ------------------------------------------------------------
# 9. Display variable list
# ------------------------------------------------------------

print("\n=== VARIABLE LIST ===")

for i, (name, vtype, lb, ub) in enumerate(
    zip(
        variable_names,
        variable_types,
        lower_bounds,
        upper_bounds
    )
):
    print(
        f"{i:3d} | {name:25s} | "
        f"Type: {vtype} | LB: {lb} | UB: {ub}"
    )

=== MILP DECISION VARIABLES ===
Cancellation variables : 25
Delay variables        : 25
Routing arc variables  : 37
Total decision variables: 87

=== VARIABLE LIST ===
  0 | x_cancel_F01              | Type: B | LB: 0.0 | UB: 1.0
  1 | x_cancel_F02              | Type: B | LB: 0.0 | UB: 1.0
  2 | x_cancel_F03              | Type: B | LB: 0.0 | UB: 1.0
  3 | x_cancel_F04              | Type: B | LB: 0.0 | UB: 1.0
  4 | x_cancel_F05              | Type: B | LB: 0.0 | UB: 1.0
  5 | x_cancel_F06              | Type: B | LB: 0.0 | UB: 1.0
  6 | x_cancel_F07              | Type: B | LB: 0.0 | UB: 1.0
  7 | x_cancel_F08              | Type: B | LB: 0.0 | UB: 1.0
  8 | x_cancel_F09              | Type: B | LB: 0.0 | UB: 1.0
  9 | x_cancel_F10              | Type: B | LB: 0.0 | UB: 1.0
 10 | x_cancel_F11              | Type: B | LB: 0.0 | UB: 1.0
 11 | x_cancel_F12              | Type: B | LB: 0.0 | UB: 1.0
 12 | x_cancel_F13              | Type: B | LB: 0.0 | UB: 1.0
 13 | x_cancel_F14              | Type: B | LB: 0.0 | UB: 1.0
 14 | x_cancel_F15              | Type: B | LB: 0.0 | UB: 1.0
 15 | x_cancel_F16              | Type: B | LB: 0.0 | UB: 1.0
 16 | x_cancel_F17              | Type: B | LB: 0.0 | UB: 1.0
 17 | x_cancel_F18              | Type: B | LB: 0.0 | UB: 1.0
 18 | x_cancel_F19              | Type: B | LB: 0.0 | UB: 1.0
 19 | x_cancel_F20              | Type: B | LB: 0.0 | UB: 1.0
 20 | x_cancel_F21              | Type: B | LB: 0.0 | UB: 1.0
 21 | x_cancel_F22              | Type: B | LB: 0.0 | UB: 1.0
 22 | x_cancel_F23              | Type: B | LB: 0.0 | UB: 1.0
 23 | x_cancel_F24              | Type: B | LB: 0.0 | UB: 1.0
 24 | x_cancel_F25              | Type: B | LB: 0.0 | UB: 1.0
 25 | d_F01                     | Type: C | LB: 0.0 | UB: 60.0
 26 | d_F02                     | Type: C | LB: 0.0 | UB: 60.0
 27 | d_F03                     | Type: C | LB: 0.0 | UB: 60.0
 28 | d_F04                     | Type: C | LB: 0.0 | UB: 60.0
 29 | d_F05                     | Type: C | LB: 0.0 | UB: 60.0
 30 | d_F06                     | Type: C | LB: 0.0 | UB: 60.0
 31 | d_F07                     | Type: C | LB: 0.0 | UB: 60.0
 32 | d_F08                     | Type: C | LB: 0.0 | UB: 60.0
 33 | d_F09                     | Type: C | LB: 0.0 | UB: 60.0
 34 | d_F10                     | Type: C | LB: 0.0 | UB: 60.0
 35 | d_F11                     | Type: C | LB: 0.0 | UB: 60.0
 36 | d_F12                     | Type: C | LB: 0.0 | UB: 60.0
 37 | d_F13                     | Type: C | LB: 0.0 | UB: 60.0
 38 | d_F14                     | Type: C | LB: 0.0 | UB: 60.0
 39 | d_F15                     | Type: C | LB: 0.0 | UB: 60.0
 40 | d_F16                     | Type: C | LB: 0.0 | UB: 60.0
 41 | d_F17                     | Type: C | LB: 0.0 | UB: 60.0
 42 | d_F18                     | Type: C | LB: 0.0 | UB: 60.0
 43 | d_F19                     | Type: C | LB: 0.0 | UB: 60.0
 44 | d_F20                     | Type: C | LB: 0.0 | UB: 60.0
 45 | d_F21                     | Type: C | LB: 0.0 | UB: 60.0
 46 | d_F22                     | Type: C | LB: 0.0 | UB: 60.0
 47 | d_F23                     | Type: C | LB: 0.0 | UB: 60.0
 48 | d_F24                     | Type: C | LB: 0.0 | UB: 60.0
 49 | d_F25                     | Type: C | LB: 0.0 | UB: 60.0
 50 | x_arc_F01_F19             | Type: B | LB: 0.0 | UB: 1.0
 51 | x_arc_F02_F03             | Type: B | LB: 0.0 | UB: 1.0
 52 | x_arc_F02_F16             | Type: B | LB: 0.0 | UB: 1.0
 53 | x_arc_F04_F05             | Type: B | LB: 0.0 | UB: 1.0
 54 | x_arc_F05_F06             | Type: B | LB: 0.0 | UB: 1.0
 55 | x_arc_F05_F25             | Type: B | LB: 0.0 | UB: 1.0
 56 | x_arc_F07_F08             | Type: B | LB: 0.0 | UB: 1.0
 57 | x_arc_F07_F13             | Type: B | LB: 0.0 | UB: 1.0
 58 | x_arc_F07_F24             | Type: B | LB: 0.0 | UB: 1.0
 59 | x_arc_F08_F09             | Type: B | LB: 0.0 | UB: 1.0
 60 | x_arc_F08_F12             | Type: B | LB: 0.0 | UB: 1.0
 61 | x_arc_F08_F22             | Type: B | LB: 0.0 | UB: 1.0
 62 | x_arc_F10_F06             | Type: B | LB: 0.0 | UB: 1.0
 63 | x_arc_F10_F11             | Type: B | LB: 0.0 | UB: 1.0
 64 | x_arc_F10_F25             | Type: B | LB: 0.0 | UB: 1.0
 65 | x_arc_F11_F09             | Type: B | LB: 0.0 | UB: 1.0
 66 | x_arc_F11_F12             | Type: B | LB: 0.0 | UB: 1.0
 67 | x_arc_F11_F22             | Type: B | LB: 0.0 | UB: 1.0
 68 | x_arc_F14_F09             | Type: B | LB: 0.0 | UB: 1.0
 69 | x_arc_F14_F12             | Type: B | LB: 0.0 | UB: 1.0
 70 | x_arc_F14_F15             | Type: B | LB: 0.0 | UB: 1.0
 71 | x_arc_F14_F22             | Type: B | LB: 0.0 | UB: 1.0
 72 | x_arc_F15_F16             | Type: B | LB: 0.0 | UB: 1.0
 73 | x_arc_F17_F09             | Type: B | LB: 0.0 | UB: 1.0
 74 | x_arc_F17_F12             | Type: B | LB: 0.0 | UB: 1.0
 75 | x_arc_F17_F15             | Type: B | LB: 0.0 | UB: 1.0
 76 | x_arc_F17_F18             | Type: B | LB: 0.0 | UB: 1.0
 77 | x_arc_F17_F22             | Type: B | LB: 0.0 | UB: 1.0
 78 | x_arc_F18_F19             | Type: B | LB: 0.0 | UB: 1.0
 79 | x_arc_F20_F19             | Type: B | LB: 0.0 | UB: 1.0
 80 | x_arc_F20_F21             | Type: B | LB: 0.0 | UB: 1.0
 81 | x_arc_F21_F09             | Type: B | LB: 0.0 | UB: 1.0
 82 | x_arc_F21_F12             | Type: B | LB: 0.0 | UB: 1.0
 83 | x_arc_F21_F22             | Type: B | LB: 0.0 | UB: 1.0
 84 | x_arc_F23_F13             | Type: B | LB: 0.0 | UB: 1.0
 85 | x_arc_F23_F24             | Type: B | LB: 0.0 | UB: 1.0
 86 | x_arc_F24_F25             | Type: B | LB: 0.0 | UB: 1.0

In [ ]:
# ============================================================
# MILP OBJECTIVE FUNCTION
# ============================================================

# Objective coefficient for every decision variable
objective = np.zeros(len(variable_names))

# ------------------------------------------------------------
# 1. Cancellation costs
# ------------------------------------------------------------

for i, flight_id in enumerate(flights_25["flight_id"]):

    flight = flights_25[
        flights_25["flight_id"] == flight_id
    ].iloc[0]

    objective[i] = flight["c_cancel"]


# ------------------------------------------------------------
# 2. Delay costs
# ------------------------------------------------------------

delay_start = len(cancel_vars)

for i, flight_id in enumerate(flights_25["flight_id"]):

    flight = flights_25[
        flights_25["flight_id"] == flight_id
    ].iloc[0]

    objective[delay_start + i] = flight["c_delay_per_min"]


# ------------------------------------------------------------
# 3. Routing arc costs
# ------------------------------------------------------------

arc_start = len(cancel_vars) + len(delay_vars)

for i, (_, arc) in enumerate(final_routing_df.iterrows()):

    ground_time = arc["ground_time"]

    objective[arc_start + i] = ground_time * 500


# ------------------------------------------------------------
# Display objective
# ------------------------------------------------------------

print("=== OBJECTIVE FUNCTION ===")

for i, (name, cost) in enumerate(
    zip(variable_names, objective)
):

    print(
        f"{i:3d} | {name:25s} | "
        f"Cost coefficient: ₹{cost:,.0f}"
    )

print("\n=== OBJECTIVE SUMMARY ===")

print(
    f"Cancellation cost coefficients: "
    f"{objective[:len(cancel_vars)].min():,.0f} "
    f"to "
    f"{objective[:len(cancel_vars)].max():,.0f}"
)

print(
    f"Delay cost per minute: "
    f"{objective[delay_start]:,.0f}"
)

print(
    f"Routing variables: "
    f"{len(arc_vars)}"
)

=== OBJECTIVE FUNCTION ===
  0 | x_cancel_F01              | Cost coefficient: ₹500,000
  1 | x_cancel_F02              | Cost coefficient: ₹500,000
  2 | x_cancel_F03              | Cost coefficient: ₹500,000
  3 | x_cancel_F04              | Cost coefficient: ₹500,000
  4 | x_cancel_F05              | Cost coefficient: ₹500,000
  5 | x_cancel_F06              | Cost coefficient: ₹500,000
  6 | x_cancel_F07              | Cost coefficient: ₹500,000
  7 | x_cancel_F08              | Cost coefficient: ₹500,000
  8 | x_cancel_F09              | Cost coefficient: ₹500,000
  9 | x_cancel_F10              | Cost coefficient: ₹500,000
 10 | x_cancel_F11              | Cost coefficient: ₹500,000
 11 | x_cancel_F12              | Cost coefficient: ₹500,000
 12 | x_cancel_F13              | Cost coefficient: ₹500,000
 13 | x_cancel_F14              | Cost coefficient: ₹500,000
 14 | x_cancel_F15              | Cost coefficient: ₹500,000
 15 | x_cancel_F16              | Cost coefficient: ₹500,000
 16 | x_cancel_F17              | Cost coefficient: ₹500,000
 17 | x_cancel_F18              | Cost coefficient: ₹500,000
 18 | x_cancel_F19              | Cost coefficient: ₹500,000
 19 | x_cancel_F20              | Cost coefficient: ₹500,000
 20 | x_cancel_F21              | Cost coefficient: ₹500,000
 21 | x_cancel_F22              | Cost coefficient: ₹500,000
 22 | x_cancel_F23              | Cost coefficient: ₹500,000
 23 | x_cancel_F24              | Cost coefficient: ₹500,000
 24 | x_cancel_F25              | Cost coefficient: ₹500,000
 25 | d_F01                     | Cost coefficient: ₹1,000
 26 | d_F02                     | Cost coefficient: ₹1,000
 27 | d_F03                     | Cost coefficient: ₹1,000
 28 | d_F04                     | Cost coefficient: ₹1,000
 29 | d_F05                     | Cost coefficient: ₹1,000
 30 | d_F06                     | Cost coefficient: ₹1,000
 31 | d_F07                     | Cost coefficient: ₹1,000
 32 | d_F08                     | Cost coefficient: ₹1,000
 33 | d_F09                     | Cost coefficient: ₹1,000
 34 | d_F10                     | Cost coefficient: ₹1,000
 35 | d_F11                     | Cost coefficient: ₹1,000
 36 | d_F12                     | Cost coefficient: ₹1,000
 37 | d_F13                     | Cost coefficient: ₹1,000
 38 | d_F14                     | Cost coefficient: ₹1,000
 39 | d_F15                     | Cost coefficient: ₹1,000
 40 | d_F16                     | Cost coefficient: ₹1,000
 41 | d_F17                     | Cost coefficient: ₹1,000
 42 | d_F18                     | Cost coefficient: ₹1,000
 43 | d_F19                     | Cost coefficient: ₹1,000
 44 | d_F20                     | Cost coefficient: ₹1,000
 45 | d_F21                     | Cost coefficient: ₹1,000
 46 | d_F22                     | Cost coefficient: ₹1,000
 47 | d_F23                     | Cost coefficient: ₹1,000
 48 | d_F24                     | Cost coefficient: ₹1,000
 49 | d_F25                     | Cost coefficient: ₹1,000
 50 | x_arc_F01_F19             | Cost coefficient: ₹160,000
 51 | x_arc_F02_F03             | Cost coefficient: ₹35,000
 52 | x_arc_F02_F16             | Cost coefficient: ₹110,000
 53 | x_arc_F04_F05             | Cost coefficient: ₹45,000
 54 | x_arc_F05_F06             | Cost coefficient: ₹30,000
 55 | x_arc_F05_F25             | Cost coefficient: ₹75,000
 56 | x_arc_F07_F08             | Cost coefficient: ₹30,000
 57 | x_arc_F07_F13             | Cost coefficient: ₹215,000
 58 | x_arc_F07_F24             | Cost coefficient: ₹65,000
 59 | x_arc_F08_F09             | Cost coefficient: ₹35,000
 60 | x_arc_F08_F12             | Cost coefficient: ₹35,000
 61 | x_arc_F08_F22             | Cost coefficient: ₹35,000
 62 | x_arc_F10_F06             | Cost coefficient: ₹115,000
 63 | x_arc_F10_F11             | Cost coefficient: ₹30,000
 64 | x_arc_F10_F25             | Cost coefficient: ₹160,000
 65 | x_arc_F11_F09             | Cost coefficient: ₹30,000
 66 | x_arc_F11_F12             | Cost coefficient: ₹30,000
 67 | x_arc_F11_F22             | Cost coefficient: ₹30,000
 68 | x_arc_F14_F09             | Cost coefficient: ₹95,000
 69 | x_arc_F14_F12             | Cost coefficient: ₹95,000
 70 | x_arc_F14_F15             | Cost coefficient: ₹30,000
 71 | x_arc_F14_F22             | Cost coefficient: ₹95,000
 72 | x_arc_F15_F16             | Cost coefficient: ₹30,000
 73 | x_arc_F17_F09             | Cost coefficient: ₹140,000
 74 | x_arc_F17_F12             | Cost coefficient: ₹140,000
 75 | x_arc_F17_F15             | Cost coefficient: ₹75,000
 76 | x_arc_F17_F18             | Cost coefficient: ₹50,000
 77 | x_arc_F17_F22             | Cost coefficient: ₹140,000
 78 | x_arc_F18_F19             | Cost coefficient: ₹45,000
 79 | x_arc_F20_F19             | Cost coefficient: ₹185,000
 80 | x_arc_F20_F21             | Cost coefficient: ₹30,000
 81 | x_arc_F21_F09             | Cost coefficient: ₹35,000
 82 | x_arc_F21_F12             | Cost coefficient: ₹35,000
 83 | x_arc_F21_F22             | Cost coefficient: ₹35,000
 84 | x_arc_F23_F13             | Cost coefficient: ₹180,000
 85 | x_arc_F23_F24             | Cost coefficient: ₹30,000
 86 | x_arc_F24_F25             | Cost coefficient: ₹35,000

=== OBJECTIVE SUMMARY ===
Cancellation cost coefficients: 500,000 to 500,000
Delay cost per minute: 1,000
Routing variables: 37

In [ ]:
# ============================================================
# FLIGHT COVERAGE CONSTRAINTS
# ============================================================

print("=== ADDING FLIGHT COVERAGE CONSTRAINTS ===")

# ------------------------------------------------------------
# 1. Create variable-index mapping
#
# This lets us find the position of every MILP variable
# inside the objective / constraint matrix.
# ------------------------------------------------------------

var_index = {
    name: i
    for i, name in enumerate(variable_names)
}

# ------------------------------------------------------------
# 2. Prepare constraint matrix
#
# One coverage constraint for every flight.
# ------------------------------------------------------------

n_flights = len(flights_25)
n_variables = len(variable_names)

coverage_matrix = lil_matrix(
    (n_flights, n_variables),
    dtype=float
)

coverage_lower = np.ones(n_flights)
coverage_upper = np.full(n_flights, np.inf)

# ------------------------------------------------------------
# 3. Build one constraint for each flight
#
# Flight must either:
#
#   - be cancelled
#   OR
#   - have an incoming routing arc
#   OR
#   - have an outgoing routing arc
#
# Constraint:
#
# x_cancel_Fi
# + incoming arcs
# + outgoing arcs >= 1
# ------------------------------------------------------------

coverage_constraints = []

for row_idx, flight_id in enumerate(
    flights_25["flight_id"]
):

    # --------------------------------------------------------
    # Cancellation variable
    # --------------------------------------------------------

    cancel_name = f"x_cancel_{flight_id}"

    coverage_matrix[
        row_idx,
        var_index[cancel_name]
    ] = 1

    # --------------------------------------------------------
    # Find incoming and outgoing arcs
    #
    # final_arcs contains tuples:
    # ('F01', 'F19')
    # ('F02', 'F03')
    # etc.
    # --------------------------------------------------------

    incoming_arcs = [
        arc
        for arc in final_arcs
        if arc[1] == flight_id
    ]

    outgoing_arcs = [
        arc
        for arc in final_arcs
        if arc[0] == flight_id
    ]

    # --------------------------------------------------------
    # Add incoming arc variables
    # --------------------------------------------------------

    for from_flight, to_flight in incoming_arcs:

        arc_name = (
            f"x_arc_{from_flight}_{to_flight}"
        )

        coverage_matrix[
            row_idx,
            var_index[arc_name]
        ] = 1

    # --------------------------------------------------------
    # Add outgoing arc variables
    # --------------------------------------------------------

    for from_flight, to_flight in outgoing_arcs:

        arc_name = (
            f"x_arc_{from_flight}_{to_flight}"
        )

        coverage_matrix[
            row_idx,
            var_index[arc_name]
        ] = 1

    # --------------------------------------------------------
    # Store information for validation
    # --------------------------------------------------------

    coverage_constraints.append({
        "flight_id": flight_id,
        "incoming_arcs": incoming_arcs,
        "outgoing_arcs": outgoing_arcs
    })


# ------------------------------------------------------------
# 4. Convert sparse matrix to CSR
# ------------------------------------------------------------

coverage_matrix = coverage_matrix.tocsr()

# ------------------------------------------------------------
# 5. Create SciPy LinearConstraint
# ------------------------------------------------------------

coverage_constraint = LinearConstraint(
    coverage_matrix,
    coverage_lower,
    coverage_upper
)

# ------------------------------------------------------------
# 6. Display summary
# ------------------------------------------------------------

print(
    f"Coverage constraints added: "
    f"{len(coverage_constraints)}"
)

print(
    f"Expected: "
    f"{len(flights_25)}"
)

# ------------------------------------------------------------
# 7. Display constraint structure
# ------------------------------------------------------------

print("\n=== COVERAGE CONSTRAINT DETAILS ===")

for item in coverage_constraints:

    print(
        f"{item['flight_id']} | "
        f"Incoming: {len(item['incoming_arcs'])} | "
        f"Outgoing: {len(item['outgoing_arcs'])}"
    )

print("\n=== COVERAGE MATRIX ===")
print(
    f"Rows (constraints): {coverage_matrix.shape[0]}"
)

print(
    f"Columns (variables): {coverage_matrix.shape[1]}"
)

print(
    f"Non-zero coefficients: "
    f"{coverage_matrix.nnz}"
)

=== ADDING FLIGHT COVERAGE CONSTRAINTS ===
Coverage constraints added: 25
Expected: 25

=== COVERAGE CONSTRAINT DETAILS ===
F01 | Incoming: 0 | Outgoing: 1
F02 | Incoming: 0 | Outgoing: 2
F03 | Incoming: 1 | Outgoing: 0
F04 | Incoming: 0 | Outgoing: 1
F05 | Incoming: 1 | Outgoing: 2
F06 | Incoming: 2 | Outgoing: 0
F07 | Incoming: 0 | Outgoing: 3
F08 | Incoming: 1 | Outgoing: 3
F09 | Incoming: 5 | Outgoing: 0
F10 | Incoming: 0 | Outgoing: 3
F11 | Incoming: 1 | Outgoing: 3
F12 | Incoming: 5 | Outgoing: 0
F13 | Incoming: 2 | Outgoing: 0
F14 | Incoming: 0 | Outgoing: 4
F15 | Incoming: 2 | Outgoing: 1
F16 | Incoming: 2 | Outgoing: 0
F17 | Incoming: 0 | Outgoing: 5
F18 | Incoming: 1 | Outgoing: 1
F19 | Incoming: 3 | Outgoing: 0
F20 | Incoming: 0 | Outgoing: 2
F21 | Incoming: 1 | Outgoing: 3
F22 | Incoming: 5 | Outgoing: 0
F23 | Incoming: 0 | Outgoing: 2
F24 | Incoming: 2 | Outgoing: 1
F25 | Incoming: 3 | Outgoing: 0

=== COVERAGE MATRIX ===
Rows (constraints): 25
Columns (variables): 87
Non-zero coefficients: 99

In [ ]:
# ============================================================
# FORCED DELAY CONSTRAINTS
# ============================================================

print("=== ADDING FORCED DELAY CONSTRAINTS ===")

# ------------------------------------------------------------
# 1. Create constraint matrix
#
# One constraint for every flight:
#
#       d_Fxx >= forced_delay
# ------------------------------------------------------------

n_flights = len(flights_25)
n_variables = len(variable_names)

delay_constraint_matrix = lil_matrix(
    (n_flights, n_variables),
    dtype=float
)

delay_lower = np.zeros(n_flights)
delay_upper = np.full(n_flights, np.inf)

# ------------------------------------------------------------
# 2. Add forced-delay constraints
# ------------------------------------------------------------

forced_delay_constraints = []

for row_idx, flight_id in enumerate(
    flights_25["flight_id"]
):

    # Variable name
    delay_name = f"d_{flight_id}"

    # Column corresponding to delay variable
    delay_idx = var_index[delay_name]

    # Coefficient of delay variable = 1
    delay_constraint_matrix[
        row_idx,
        delay_idx
    ] = 1

    # Get forced delay from dataset
    flight = flights_25[
        flights_25["flight_id"] == flight_id
    ].iloc[0]

    forced_delay = float(
        flight["forced_delay"]
    )

    # Constraint:
    #
    # d_Fxx >= forced_delay
    #
    delay_lower[row_idx] = forced_delay

    forced_delay_constraints.append({
        "flight_id": flight_id,
        "forced_delay": forced_delay,
        "variable": delay_name
    })

# ------------------------------------------------------------
# 3. Convert to CSR format
# ------------------------------------------------------------

delay_constraint_matrix = (
    delay_constraint_matrix.tocsr()
)

# ------------------------------------------------------------
# 4. Create LinearConstraint
# ------------------------------------------------------------

delay_constraint = LinearConstraint(
    delay_constraint_matrix,
    delay_lower,
    delay_upper
)

# ------------------------------------------------------------
# 5. Display results
# ------------------------------------------------------------

print(
    f"Forced delay constraints added: "
    f"{len(forced_delay_constraints)}"
)

print(
    f"Expected: {len(flights_25)}"
)

print("\n=== FORCED DELAY CONSTRAINT DETAILS ===")

for item in forced_delay_constraints:

    print(
        f"{item['flight_id']} | "
        f"{item['variable']} >= "
        f"{item['forced_delay']:.0f} min"
    )

print("\n=== DELAY CONSTRAINT MATRIX ===")

print(
    f"Rows (constraints): "
    f"{delay_constraint_matrix.shape[0]}"
)

print(
    f"Columns (variables): "
    f"{delay_constraint_matrix.shape[1]}"
)

print(
    f"Non-zero coefficients: "
    f"{delay_constraint_matrix.nnz}"
)

=== ADDING FORCED DELAY CONSTRAINTS ===
Forced delay constraints added: 25
Expected: 25

=== FORCED DELAY CONSTRAINT DETAILS ===
F01 | d_F01 >= 120 min
F02 | d_F02 >= 0 min
F03 | d_F03 >= 0 min
F04 | d_F04 >= 0 min
F05 | d_F05 >= 0 min
F06 | d_F06 >= 0 min
F07 | d_F07 >= 0 min
F08 | d_F08 >= 0 min
F09 | d_F09 >= 0 min
F10 | d_F10 >= 0 min
F11 | d_F11 >= 0 min
F12 | d_F12 >= 150 min
F13 | d_F13 >= 0 min
F14 | d_F14 >= 0 min
F15 | d_F15 >= 0 min
F16 | d_F16 >= 0 min
F17 | d_F17 >= 0 min
F18 | d_F18 >= 90 min
F19 | d_F19 >= 0 min
F20 | d_F20 >= 0 min
F21 | d_F21 >= 0 min
F22 | d_F22 >= 0 min
F23 | d_F23 >= 0 min
F24 | d_F24 >= 0 min
F25 | d_F25 >= 0 min

=== DELAY CONSTRAINT MATRIX ===
Rows (constraints): 25
Columns (variables): 87
Non-zero coefficients: 25

In [ ]:
# ============================================================
# UPDATE DELAY VARIABLE UPPER BOUND
# ============================================================

MAX_DELAY = 180.0

# Delay variables occupy the positions immediately
# after the cancellation variables.

delay_start = len(cancel_vars)
delay_end = delay_start + len(delay_vars)

for i in range(delay_start, delay_end):
    upper_bounds[i] = MAX_DELAY

print("=== UPDATED DELAY BOUNDS ===")
print(f"Maximum allowed additional delay: {MAX_DELAY:.0f} minutes")

print("\nDelay variable bounds:")

for i, flight_id in enumerate(flights_25["flight_id"]):

    idx = delay_start + i

    print(
        f"d_{flight_id:3s} | "
        f"LB: {lower_bounds[idx]:.0f} | "
        f"UB: {upper_bounds[idx]:.0f}"
    )

=== UPDATED DELAY BOUNDS ===
Maximum allowed additional delay: 180 minutes

Delay variable bounds:
d_F01 | LB: 0 | UB: 180
d_F02 | LB: 0 | UB: 180
d_F03 | LB: 0 | UB: 180
d_F04 | LB: 0 | UB: 180
d_F05 | LB: 0 | UB: 180
d_F06 | LB: 0 | UB: 180
d_F07 | LB: 0 | UB: 180
d_F08 | LB: 0 | UB: 180
d_F09 | LB: 0 | UB: 180
d_F10 | LB: 0 | UB: 180
d_F11 | LB: 0 | UB: 180
d_F12 | LB: 0 | UB: 180
d_F13 | LB: 0 | UB: 180
d_F14 | LB: 0 | UB: 180
d_F15 | LB: 0 | UB: 180
d_F16 | LB: 0 | UB: 180
d_F17 | LB: 0 | UB: 180
d_F18 | LB: 0 | UB: 180
d_F19 | LB: 0 | UB: 180
d_F20 | LB: 0 | UB: 180
d_F21 | LB: 0 | UB: 180
d_F22 | LB: 0 | UB: 180
d_F23 | LB: 0 | UB: 180
d_F24 | LB: 0 | UB: 180
d_F25 | LB: 0 | UB: 180

In [ ]:
# ============================================================
# ROUTING CONTINUITY CONSTRAINTS
# ============================================================

print("=== ADDING ROUTING CONTINUITY CONSTRAINTS ===")

continuity_constraints = []

# ------------------------------------------------------------
# Create a mapping:
# variable name -> column index
# ------------------------------------------------------------

variable_index = {
    name: i
    for i, name in enumerate(variable_names)
}

# ------------------------------------------------------------
# Arc variables start after cancellation + delay variables
# ------------------------------------------------------------

arc_start = len(cancel_vars) + len(delay_vars)

# ------------------------------------------------------------
# Build continuity constraints for every flight
#
# For each flight:
#
# Incoming arcs - Outgoing arcs = 0
#
# This ensures that if a flight is connected to another
# flight before it, the routing flow is consistent.
# ------------------------------------------------------------

for flight_id in flights_25["flight_id"]:

    # Find incoming arcs
    incoming_arcs = [
        arc for arc in final_arcs
        if arc[1] == flight_id
    ]

    # Find outgoing arcs
    outgoing_arcs = [
        arc for arc in final_arcs
        if arc[0] == flight_id
    ]

    # --------------------------------------------------------
    # Build coefficient dictionary for this constraint
    # --------------------------------------------------------

    coefficients = {}

    # Incoming arcs get +1
    for from_flight, to_flight in incoming_arcs:

        arc_name = f"x_arc_{from_flight}_{to_flight}"
        col_index = variable_index[arc_name]

        coefficients[col_index] = (
            coefficients.get(col_index, 0) + 1
        )

    # Outgoing arcs get -1
    for from_flight, to_flight in outgoing_arcs:

        arc_name = f"x_arc_{from_flight}_{to_flight}"
        col_index = variable_index[arc_name]

        coefficients[col_index] = (
            coefficients.get(col_index, 0) - 1
        )

    # --------------------------------------------------------
    # Store constraint information
    # --------------------------------------------------------

    continuity_constraints.append({
        "flight_id": flight_id,
        "coefficients": coefficients,
        "incoming_count": len(incoming_arcs),
        "outgoing_count": len(outgoing_arcs)
    })


# ------------------------------------------------------------
# DISPLAY
# ------------------------------------------------------------

print(
    f"Routing continuity constraints prepared: "
    f"{len(continuity_constraints)}"
)

print(
    f"Expected: {len(flights_25)}"
)

print("\n=== ROUTING CONTINUITY DETAILS ===")

for item in continuity_constraints:

    print(
        f"{item['flight_id']} | "
        f"Incoming: {item['incoming_count']} | "
        f"Outgoing: {item['outgoing_count']}"
    )


# ============================================================
# BUILD CONTINUITY MATRIX
# ============================================================

n_constraints = len(continuity_constraints)
n_variables = len(variable_names)

continuity_matrix = lil_matrix(
    (n_constraints, n_variables),
    dtype=float
)

for row, item in enumerate(continuity_constraints):

    for col, coefficient in item["coefficients"].items():

        continuity_matrix[row, col] = coefficient


continuity_matrix = continuity_matrix.tocsr()


# ------------------------------------------------------------
# Equality bounds
#
# Incoming - Outgoing = 0
# ------------------------------------------------------------

continuity_lb = np.zeros(n_constraints)
continuity_ub = np.zeros(n_constraints)


print("\n=== ROUTING CONTINUITY MATRIX ===")

print(
    f"Rows (constraints): "
    f"{continuity_matrix.shape[0]}"
)

print(
    f"Columns (variables): "
    f"{continuity_matrix.shape[1]}"
)

print(
    f"Non-zero coefficients: "
    f"{continuity_matrix.nnz}"
)

=== ADDING ROUTING CONTINUITY CONSTRAINTS ===
Routing continuity constraints prepared: 25
Expected: 25

=== ROUTING CONTINUITY DETAILS ===
F01 | Incoming: 0 | Outgoing: 1
F02 | Incoming: 0 | Outgoing: 2
F03 | Incoming: 1 | Outgoing: 0
F04 | Incoming: 0 | Outgoing: 1
F05 | Incoming: 1 | Outgoing: 2
F06 | Incoming: 2 | Outgoing: 0
F07 | Incoming: 0 | Outgoing: 3
F08 | Incoming: 1 | Outgoing: 3
F09 | Incoming: 5 | Outgoing: 0
F10 | Incoming: 0 | Outgoing: 3
F11 | Incoming: 1 | Outgoing: 3
F12 | Incoming: 5 | Outgoing: 0
F13 | Incoming: 2 | Outgoing: 0
F14 | Incoming: 0 | Outgoing: 4
F15 | Incoming: 2 | Outgoing: 1
F16 | Incoming: 2 | Outgoing: 0
F17 | Incoming: 0 | Outgoing: 5
F18 | Incoming: 1 | Outgoing: 1
F19 | Incoming: 3 | Outgoing: 0
F20 | Incoming: 0 | Outgoing: 2
F21 | Incoming: 1 | Outgoing: 3
F22 | Incoming: 5 | Outgoing: 0
F23 | Incoming: 0 | Outgoing: 2
F24 | Incoming: 2 | Outgoing: 1
F25 | Incoming: 3 | Outgoing: 0

=== ROUTING CONTINUITY MATRIX ===
Rows (constraints): 25
Columns (variables): 87
Non-zero coefficients: 74

In [ ]:
# ============================================================
# FLIGHT CANCELLATION - ROUTING CONSISTENCY CONSTRAINTS
# ============================================================

print("=== ADDING CANCELLATION-ROUTING CONSISTENCY CONSTRAINTS ===")

cancellation_routing_constraints = []

# Map flight ID -> cancellation variable index
cancel_index = {
    flight_id: i
    for i, flight_id in enumerate(flights_25["flight_id"])
}

# Starting index of routing variables
arc_start = len(cancel_vars) + len(delay_vars)

for j, (from_flight, to_flight) in enumerate(final_arcs):

    arc_var_index = arc_start + j

    from_cancel_index = cancel_index[from_flight]
    to_cancel_index = cancel_index[to_flight]

    # x_arc + x_cancel_from <= 1
    row = np.zeros(len(variable_names))

    row[arc_var_index] = 1
    row[from_cancel_index] = 1

    cancellation_routing_constraints.append(
        (
            from_flight,
            to_flight,
            "from_cancel",
            row
        )
    )

    # x_arc + x_cancel_to <= 1
    row = np.zeros(len(variable_names))

    row[arc_var_index] = 1
    row[to_cancel_index] = 1

    cancellation_routing_constraints.append(
        (
            from_flight,
            to_flight,
            "to_cancel",
            row
        )
    )


print(
    "Cancellation-routing constraints prepared:",
    len(cancellation_routing_constraints)
)

print(
    "Expected:",
    2 * len(final_arcs)
)

# ------------------------------------------------------------
# Display details
# ------------------------------------------------------------

print("\n=== CANCELLATION-ROUTING DETAILS ===")

for from_flight, to_flight, direction, row in (
    cancellation_routing_constraints
):

    if direction == "from_cancel":
        print(
            f"{from_flight} -> {to_flight} | "
            f"x_arc + x_cancel_{from_flight} <= 1"
        )

    else:
        print(
            f"{from_flight} -> {to_flight} | "
            f"x_arc + x_cancel_{to_flight} <= 1"
        )


# ------------------------------------------------------------
# Build matrix
# ------------------------------------------------------------

if cancellation_routing_constraints:

    cancellation_routing_matrix = np.vstack(
        [
            row
            for _, _, _, row
            in cancellation_routing_constraints
        ]
    )

else:

    cancellation_routing_matrix = np.zeros(
        (0, len(variable_names))
    )


print("\n=== CANCELLATION-ROUTING MATRIX ===")

print(
    "Rows (constraints):",
    cancellation_routing_matrix.shape[0]
)

print(
    "Columns (variables):",
    cancellation_routing_matrix.shape[1]
)

print(
    "Non-zero coefficients:",
    np.count_nonzero(cancellation_routing_matrix)
)

=== ADDING CANCELLATION-ROUTING CONSISTENCY CONSTRAINTS ===
Cancellation-routing constraints prepared: 74
Expected: 74

=== CANCELLATION-ROUTING DETAILS ===
F01 -> F19 | x_arc + x_cancel_F01 <= 1
F01 -> F19 | x_arc + x_cancel_F19 <= 1
F02 -> F03 | x_arc + x_cancel_F02 <= 1
F02 -> F03 | x_arc + x_cancel_F03 <= 1
F02 -> F16 | x_arc + x_cancel_F02 <= 1
F02 -> F16 | x_arc + x_cancel_F16 <= 1
F04 -> F05 | x_arc + x_cancel_F04 <= 1
F04 -> F05 | x_arc + x_cancel_F05 <= 1
F05 -> F06 | x_arc + x_cancel_F05 <= 1
F05 -> F06 | x_arc + x_cancel_F06 <= 1
F05 -> F25 | x_arc + x_cancel_F05 <= 1
F05 -> F25 | x_arc + x_cancel_F25 <= 1
F07 -> F08 | x_arc + x_cancel_F07 <= 1
F07 -> F08 | x_arc + x_cancel_F08 <= 1
F07 -> F13 | x_arc + x_cancel_F07 <= 1
F07 -> F13 | x_arc + x_cancel_F13 <= 1
F07 -> F24 | x_arc + x_cancel_F07 <= 1
F07 -> F24 | x_arc + x_cancel_F24 <= 1
F08 -> F09 | x_arc + x_cancel_F08 <= 1
F08 -> F09 | x_arc + x_cancel_F09 <= 1
F08 -> F12 | x_arc + x_cancel_F08 <= 1
F08 -> F12 | x_arc + x_cancel_F12 <= 1
F08 -> F22 | x_arc + x_cancel_F08 <= 1
F08 -> F22 | x_arc + x_cancel_F22 <= 1
F10 -> F06 | x_arc + x_cancel_F10 <= 1
F10 -> F06 | x_arc + x_cancel_F06 <= 1
F10 -> F11 | x_arc + x_cancel_F10 <= 1
F10 -> F11 | x_arc + x_cancel_F11 <= 1
F10 -> F25 | x_arc + x_cancel_F10 <= 1
F10 -> F25 | x_arc + x_cancel_F25 <= 1
F11 -> F09 | x_arc + x_cancel_F11 <= 1
F11 -> F09 | x_arc + x_cancel_F09 <= 1
F11 -> F12 | x_arc + x_cancel_F11 <= 1
F11 -> F12 | x_arc + x_cancel_F12 <= 1
F11 -> F22 | x_arc + x_cancel_F11 <= 1
F11 -> F22 | x_arc + x_cancel_F22 <= 1
F14 -> F09 | x_arc + x_cancel_F14 <= 1
F14 -> F09 | x_arc + x_cancel_F09 <= 1
F14 -> F12 | x_arc + x_cancel_F14 <= 1
F14 -> F12 | x_arc + x_cancel_F12 <= 1
F14 -> F15 | x_arc + x_cancel_F14 <= 1
F14 -> F15 | x_arc + x_cancel_F15 <= 1
F14 -> F22 | x_arc + x_cancel_F14 <= 1
F14 -> F22 | x_arc + x_cancel_F22 <= 1
F15 -> F16 | x_arc + x_cancel_F15 <= 1
F15 -> F16 | x_arc + x_cancel_F16 <= 1
F17 -> F09 | x_arc + x_cancel_F17 <= 1
F17 -> F09 | x_arc + x_cancel_F09 <= 1
F17 -> F12 | x_arc + x_cancel_F17 <= 1
F17 -> F12 | x_arc + x_cancel_F12 <= 1
F17 -> F15 | x_arc + x_cancel_F17 <= 1
F17 -> F15 | x_arc + x_cancel_F15 <= 1
F17 -> F18 | x_arc + x_cancel_F17 <= 1
F17 -> F18 | x_arc + x_cancel_F18 <= 1
F17 -> F22 | x_arc + x_cancel_F17 <= 1
F17 -> F22 | x_arc + x_cancel_F22 <= 1
F18 -> F19 | x_arc + x_cancel_F18 <= 1
F18 -> F19 | x_arc + x_cancel_F19 <= 1
F20 -> F19 | x_arc + x_cancel_F20 <= 1
F20 -> F19 | x_arc + x_cancel_F19 <= 1
F20 -> F21 | x_arc + x_cancel_F20 <= 1
F20 -> F21 | x_arc + x_cancel_F21 <= 1
F21 -> F09 | x_arc + x_cancel_F21 <= 1
F21 -> F09 | x_arc + x_cancel_F09 <= 1
F21 -> F12 | x_arc + x_cancel_F21 <= 1
F21 -> F12 | x_arc + x_cancel_F12 <= 1
F21 -> F22 | x_arc + x_cancel_F21 <= 1
F21 -> F22 | x_arc + x_cancel_F22 <= 1
F23 -> F13 | x_arc + x_cancel_F23 <= 1
F23 -> F13 | x_arc + x_cancel_F13 <= 1
F23 -> F24 | x_arc + x_cancel_F23 <= 1
F23 -> F24 | x_arc + x_cancel_F24 <= 1
F24 -> F25 | x_arc + x_cancel_F24 <= 1
F24 -> F25 | x_arc + x_cancel_F25 <= 1

=== CANCELLATION-ROUTING MATRIX ===
Rows (constraints): 74
Columns (variables): 87
Non-zero coefficients: 148

In [ ]:
# ============================================================
# DELAY - ROUTING FEASIBILITY CONSTRAINTS
# ============================================================

print("=== ADDING DELAY-ROUTING CONSTRAINTS ===")

delay_routing_constraints = []

# ------------------------------------------------------------
# 1. Map each flight to its delay-variable index
# ------------------------------------------------------------

delay_index = {
    flight_id: len(cancel_vars) + i
    for i, flight_id in enumerate(flights_25["flight_id"])
}

# ------------------------------------------------------------
# 2. Starting index of routing variables
# ------------------------------------------------------------

arc_start = len(cancel_vars) + len(delay_vars)

# ------------------------------------------------------------
# 3. Minimum turnaround time
# ------------------------------------------------------------

MIN_REST = 30

# Big-M for conditional routing constraint
BIG_M = 10000

# ------------------------------------------------------------
# 4. Build one constraint for every routing arc
# ------------------------------------------------------------

for j, (from_flight, to_flight) in enumerate(final_arcs):

    # --------------------------------------------------------
    # Get flight information
    # --------------------------------------------------------

    from_row = flights_25[
        flights_25["flight_id"] == from_flight
    ].iloc[0]

    to_row = flights_25[
        flights_25["flight_id"] == to_flight
    ].iloc[0]

    # Scheduled arrival of first flight
    arrival_time = from_row["sta"]

    # Scheduled departure of second flight
    departure_time = to_row["std"]

    # Scheduled ground time
    ground_time = departure_time - arrival_time

    # --------------------------------------------------------
    # Variable indices
    # --------------------------------------------------------

    from_delay_index = delay_index[from_flight]
    to_delay_index = delay_index[to_flight]

    arc_var_index = arc_start + j

    # --------------------------------------------------------
    # Constraint:
    #
    # STA(F1) + d(F1) + MIN_REST
    #       <=
    # STD(F2) + d(F2) + M(1 - x_arc)
    #
    # Rearranged:
    #
    # d(F1) - d(F2) + M*x_arc
    #       <=
    # ground_time - MIN_REST + M
    # --------------------------------------------------------

    row = np.zeros(len(variable_names))

    row[from_delay_index] = 1
    row[to_delay_index] = -1
    row[arc_var_index] = BIG_M

    rhs = (
        ground_time
        - MIN_REST
        + BIG_M
    )

    delay_routing_constraints.append(
        {
            "from": from_flight,
            "to": to_flight,
            "ground_time": ground_time,
            "rhs": rhs,
            "row": row
        }
    )


# ------------------------------------------------------------
# 5. Display summary
# ------------------------------------------------------------

print(
    "Delay-routing constraints prepared:",
    len(delay_routing_constraints)
)

print(
    "Expected:",
    len(final_arcs)
)


# ------------------------------------------------------------
# 6. Display constraint details
# ------------------------------------------------------------

print("\n=== DELAY-ROUTING DETAILS ===")

for constraint in delay_routing_constraints:

    print(
        f"{constraint['from']} -> {constraint['to']} | "
        f"Scheduled ground time: "
        f"{constraint['ground_time']} min | "
        f"Minimum turnaround: {MIN_REST} min"
    )


# ------------------------------------------------------------
# 7. Build constraint matrix
# ------------------------------------------------------------

if delay_routing_constraints:

    delay_routing_matrix = np.vstack(
        [
            constraint["row"]
            for constraint in delay_routing_constraints
        ]
    )

    delay_routing_rhs = np.array(
        [
            constraint["rhs"]
            for constraint in delay_routing_constraints
        ]
    )

else:

    delay_routing_matrix = np.zeros(
        (0, len(variable_names))
    )

    delay_routing_rhs = np.array([])


# ------------------------------------------------------------
# 8. Display matrix information
# ------------------------------------------------------------

print("\n=== DELAY-ROUTING MATRIX ===")

print(
    "Rows (constraints):",
    delay_routing_matrix.shape[0]
)

print(
    "Columns (variables):",
    delay_routing_matrix.shape[1]
)

print(
    "Non-zero coefficients:",
    np.count_nonzero(delay_routing_matrix)
)

=== ADDING DELAY-ROUTING CONSTRAINTS ===
Delay-routing constraints prepared: 37
Expected: 37

=== DELAY-ROUTING DETAILS ===
F01 -> F19 | Scheduled ground time: 440 min | Minimum turnaround: 30 min
F02 -> F03 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F02 -> F16 | Scheduled ground time: 220 min | Minimum turnaround: 30 min
F04 -> F05 | Scheduled ground time: 90 min | Minimum turnaround: 30 min
F05 -> F06 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F05 -> F25 | Scheduled ground time: 150 min | Minimum turnaround: 30 min
F07 -> F08 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F07 -> F13 | Scheduled ground time: 430 min | Minimum turnaround: 30 min
F07 -> F24 | Scheduled ground time: 130 min | Minimum turnaround: 30 min
F08 -> F09 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F08 -> F12 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F08 -> F22 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F10 -> F06 | Scheduled ground time: 230 min | Minimum turnaround: 30 min
F10 -> F11 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F10 -> F25 | Scheduled ground time: 320 min | Minimum turnaround: 30 min
F11 -> F09 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F11 -> F12 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F11 -> F22 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F14 -> F09 | Scheduled ground time: 190 min | Minimum turnaround: 30 min
F14 -> F12 | Scheduled ground time: 190 min | Minimum turnaround: 30 min
F14 -> F15 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F14 -> F22 | Scheduled ground time: 190 min | Minimum turnaround: 30 min
F15 -> F16 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F17 -> F09 | Scheduled ground time: 280 min | Minimum turnaround: 30 min
F17 -> F12 | Scheduled ground time: 280 min | Minimum turnaround: 30 min
F17 -> F15 | Scheduled ground time: 150 min | Minimum turnaround: 30 min
F17 -> F18 | Scheduled ground time: 100 min | Minimum turnaround: 30 min
F17 -> F22 | Scheduled ground time: 280 min | Minimum turnaround: 30 min
F18 -> F19 | Scheduled ground time: 180 min | Minimum turnaround: 30 min
F20 -> F19 | Scheduled ground time: 370 min | Minimum turnaround: 30 min
F20 -> F21 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F21 -> F09 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F21 -> F12 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F21 -> F22 | Scheduled ground time: 70 min | Minimum turnaround: 30 min
F23 -> F13 | Scheduled ground time: 360 min | Minimum turnaround: 30 min
F23 -> F24 | Scheduled ground time: 60 min | Minimum turnaround: 30 min
F24 -> F25 | Scheduled ground time: 70 min | Minimum turnaround: 30 min

=== DELAY-ROUTING MATRIX ===
Rows (constraints): 37
Columns (variables): 87
Non-zero coefficients: 111

In [ ]:
# ============================================================
# COMBINE ALL MILP CONSTRAINTS
# ============================================================

print("=== COMBINING MILP CONSTRAINTS ===")

# ------------------------------------------------------------
# 1. Convert all matrices to compatible sparse format
# ------------------------------------------------------------

from scipy.sparse import vstack, csr_matrix

coverage_matrix_sparse = csr_matrix(coverage_matrix)
delay_matrix_sparse = csr_matrix(delay_constraint_matrix)
continuity_matrix_sparse = csr_matrix(continuity_matrix)
delay_routing_matrix_sparse = csr_matrix(delay_routing_matrix)


# ------------------------------------------------------------
# 2. Combine all constraint matrices
# ------------------------------------------------------------

constraint_matrix = vstack([
    coverage_matrix_sparse,
    delay_matrix_sparse,
    continuity_matrix_sparse,
    delay_routing_matrix_sparse
]).tocsr()


# ------------------------------------------------------------
# 3. Combine lower bounds
# ------------------------------------------------------------

delay_routing_lower = np.full(
    len(delay_routing_constraints),
    -np.inf
)

constraint_lower = np.concatenate([
    coverage_lower,
    delay_lower,
    continuity_lb,
    delay_routing_lower
])


# ------------------------------------------------------------
# 4. Combine upper bounds
# ------------------------------------------------------------

constraint_upper = np.concatenate([
    coverage_upper,
    delay_upper,
    continuity_ub,
    delay_routing_rhs
])


# ------------------------------------------------------------
# 5. Create final LinearConstraint object
# ------------------------------------------------------------

all_constraints = LinearConstraint(
    constraint_matrix,
    constraint_lower,
    constraint_upper
)


# ------------------------------------------------------------
# 6. Display final constraint information
# ------------------------------------------------------------

print("\n=== FINAL CONSTRAINT MATRIX ===")

print(
    "Rows (total constraints):",
    constraint_matrix.shape[0]
)

print(
    "Columns (decision variables):",
    constraint_matrix.shape[1]
)

print(
    "Non-zero coefficients:",
    constraint_matrix.nnz
)


print("\n=== CONSTRAINT BREAKDOWN ===")

print(
    "Flight coverage constraints    :",
    coverage_matrix.shape[0]
)

print(
    "Forced delay constraints       :",
    delay_constraint_matrix.shape[0]
)

print(
    "Routing continuity constraints :",
    continuity_matrix.shape[0]
)

print(
    "Delay-routing constraints      :",
    delay_routing_matrix.shape[0]
)

print(
    "---------------------------------------"
)

print(
    "Total constraints              :",
    constraint_matrix.shape[0]
)

=== COMBINING MILP CONSTRAINTS ===

=== FINAL CONSTRAINT MATRIX ===
Rows (total constraints): 112
Columns (decision variables): 87
Non-zero coefficients: 309

=== CONSTRAINT BREAKDOWN ===
Flight coverage constraints    : 25
Forced delay constraints       : 25
Routing continuity constraints : 25
Delay-routing constraints      : 37
---------------------------------------
Total constraints              : 112

In [ ]:
# ============================================================
# FINAL PRESOLVER HANDOFF
# ============================================================

print("=" * 70)
print("FINAL PRESOLVER HANDOFF FOR MILP SOLVER")
print("=" * 70)

# ------------------------------------------------------------
# 1. FLIGHT DATA
# ------------------------------------------------------------

print("\n=== FLIGHTS ===")
print("Number of flights:", len(flights_25))
print("Flight IDs:", list(flights_25["flight_id"]))


# ------------------------------------------------------------
# 2. FINAL ROUTING ARCS
# ------------------------------------------------------------

print("\n=== FINAL ROUTING ARCS ===")
print("Number of routing arcs:", len(final_arcs))

for arc in final_arcs:
    print(f"  {arc[0]} -> {arc[1]}")


# ------------------------------------------------------------
# 3. DECISION VARIABLES
# ------------------------------------------------------------

print("\n=== DECISION VARIABLES ===")

print("Cancellation variables:", len(cancel_vars))
print("Delay variables:", len(delay_vars))
print("Routing variables:", len(arc_vars))
print("Total variables:", len(variable_names))

print("\nVariable ordering:")
print("  [Cancellation variables]")
print("  [Delay variables]")
print("  [Routing variables]")


# ------------------------------------------------------------
# 4. VARIABLE BOUNDS
# ------------------------------------------------------------

print("\n=== VARIABLE BOUNDS ===")

print("Cancellation bounds: 0 to 1")
print("Delay bounds: 0 to 60")
print("Routing bounds: 0 to 1")


# ------------------------------------------------------------
# 5. OBJECTIVE
# ------------------------------------------------------------

print("\n=== OBJECTIVE ===")

print("Objective vector length:", len(objective))

print("Cancellation cost coefficients:",
      objective[:len(cancel_vars)].min(),
      "to",
      objective[:len(cancel_vars)].max())

print("Delay cost per minute:",
      objective[len(cancel_vars)])

print("Routing objective coefficients:")
print(
    objective[
        len(cancel_vars) + len(delay_vars):
    ]
)


# ------------------------------------------------------------
# 6. CONSTRAINT BREAKDOWN
# ------------------------------------------------------------

print("\n=== CONSTRAINT BREAKDOWN ===")

print("Flight coverage constraints:",
      coverage_matrix.shape[0])

print("Forced delay constraints:",
      delay_constraint_matrix.shape[0])

print("Routing continuity constraints:",
      continuity_matrix.shape[0])

print("Delay-routing constraints:",
      delay_routing_matrix.shape[0])

print("TOTAL CONSTRAINTS:",
      constraint_matrix.shape[0])


# ------------------------------------------------------------
# 7. FINAL MATRIX DIMENSIONS
# ------------------------------------------------------------

print("\n=== FINAL MILP DIMENSIONS ===")

print("Constraint matrix shape:",
      constraint_matrix.shape)

print("Expected:",
      f"{constraint_matrix.shape[0]} constraints × "
      f"{constraint_matrix.shape[1]} variables")

print("Non-zero coefficients:",
      constraint_matrix.nnz)


# ------------------------------------------------------------
# 8. SOLVER INPUT OBJECTS
# ------------------------------------------------------------

print("\n=== OBJECTS TO PASS TO SOLVER ===")

print("objective")
print("variable_names")
print("variable_types")
print("lower_bounds")
print("upper_bounds")
print("integrality")
print("constraint_matrix")
print("constraint_lower")
print("constraint_upper")


# ------------------------------------------------------------
# 9. IMPORTANT NOTE
# ------------------------------------------------------------

print("\n=== PRESOLVER STATUS ===")

print("Presolver complete.")
print("MILP solving has NOT been performed in this notebook.")
print("The above objects form the interface to the solver.")

======================================================================
FINAL PRESOLVER HANDOFF FOR MILP SOLVER
======================================================================

=== FLIGHTS ===
Number of flights: 25
Flight IDs: ['F01', 'F02', 'F03', 'F04', 'F05', 'F06', 'F07', 'F08', 'F09', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25']

=== FINAL ROUTING ARCS ===
Number of routing arcs: 37
  F01 -> F19
  F02 -> F03
  F02 -> F16
  F04 -> F05
  F05 -> F06
  F05 -> F25
  F07 -> F08
  F07 -> F13
  F07 -> F24
  F08 -> F09
  F08 -> F12
  F08 -> F22
  F10 -> F06
  F10 -> F11
  F10 -> F25
  F11 -> F09
  F11 -> F12
  F11 -> F22
  F14 -> F09
  F14 -> F12
  F14 -> F15
  F14 -> F22
  F15 -> F16
  F17 -> F09
  F17 -> F12
  F17 -> F15
  F17 -> F18
  F17 -> F22
  F18 -> F19
  F20 -> F19
  F20 -> F21
  F21 -> F09
  F21 -> F12
  F21 -> F22
  F23 -> F13
  F23 -> F24
  F24 -> F25

=== DECISION VARIABLES ===
Cancellation variables: 25
Delay variables: 25
Routing variables: 37
Total variables: 87

Variable ordering:
  [Cancellation variables]
  [Delay variables]
  [Routing variables]

=== VARIABLE BOUNDS ===
Cancellation bounds: 0 to 1
Delay bounds: 0 to 60
Routing bounds: 0 to 1

=== OBJECTIVE ===
Objective vector length: 87
Cancellation cost coefficients: 500000.0 to 500000.0
Delay cost per minute: 1000.0
Routing objective coefficients:
[160000.  35000. 110000.  45000.  30000.  75000.  30000. 215000.  65000.
  35000.  35000.  35000. 115000.  30000. 160000.  30000.  30000.  30000.
  95000.  95000.  30000.  95000.  30000. 140000. 140000.  75000.  50000.
 140000.  45000. 185000.  30000.  35000.  35000.  35000. 180000.  30000.
  35000.]

=== CONSTRAINT BREAKDOWN ===
Flight coverage constraints: 25
Forced delay constraints: 25
Routing continuity constraints: 25
Delay-routing constraints: 37
TOTAL CONSTRAINTS: 112

=== FINAL MILP DIMENSIONS ===
Constraint matrix shape: (112, 87)
Expected: 112 constraints × 87 variables
Non-zero coefficients: 309

=== OBJECTS TO PASS TO SOLVER ===
objective
variable_names
variable_types
lower_bounds
upper_bounds
integrality
constraint_matrix
constraint_lower
constraint_upper

=== PRESOLVER STATUS ===
Presolver complete.
MILP solving has NOT been performed in this notebook.
The above objects form the interface to the solver.

In [ ]:
import pickle
import numpy as np

integrality = np.array([
    1 if vtype == "B" else 0
    for vtype in variable_types
])

handoff = {
    "objective": objective,
    "variable_names": variable_names,
    "variable_types": variable_types,
    "lower_bounds": lower_bounds,
    "upper_bounds": upper_bounds,
    "constraint_matrix": constraint_matrix,
    "constraint_lower": constraint_lower,
    "constraint_upper": constraint_upper,
    "integrality": integrality
}

with open("presolver_milp_handoff.pkl", "wb") as f:
    pickle.dump(handoff, f)

print("Handoff file created successfully!")

Handoff file created successfully!